# Generated by Django 4.2 on 2023-04-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(default="no", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
