# Generated by Django 4.2 on 2023-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
