# Generated by Django 4.2 on 2023-04-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_category_blogpost_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="tags",),
    ]
