# Generated by Django 4.2 on 2023-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_aboutus_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus", options={"verbose_name_plural": "About Us"},
        ),
        migrations.AlterModelOptions(
            name="contactus", options={"verbose_name_plural": "Contact Us"},
        ),
        migrations.AddField(
            model_name="aboutus",
            name="about_us_image",
            field=models.ImageField(default="ser", upload_to="about-us"),
            preserve_default=False,
        ),
    ]
