# Generated by Django 4.2 on 2023-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_aboutus_options_alter_contactus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(default="ok", upload_to="category_image/"),
            preserve_default=False,
        ),
    ]
