# Generated by Django 4.2 on 2023-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_category_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="New", max_length=100),
            preserve_default=False,
        ),
    ]
